root = "." # The root directory of your project
tmp_dir = "tmp" # Temporary directory for build artifacts

[build] # Build configuration
    bin = "main" # The name of the binary to be generated after building project
    cmd = "go build -o {{.Output}} {{.Input}}" # Command to build the project
    exclude = ["tmp/*", "client/*"] # Exclude files and directories from the build
    include = ["**/*.go"] # Include only Go files in the build
    ignore = ["tmp/*"] # Ignore temporary files